In [1]:
import pandas as pd
import numpy as np

In [8]:
df_ord=pd.read_excel('Raw Data.xlsx',sheet_name='orders')
df_ord=df_ord[['Order ID','Order Date','Customer ID','Product ID','Quantity']]
df_cust = pd.read_excel('Raw Data.xlsx',sheet_name = 'customers')
df_prod = pd.read_excel('Raw Data.xlsx',sheet_name = 'products')

In [9]:
df_ord.head()

        Order ID Order Date     Customer ID Product ID  Quantity
0  QEV-37451-860 2019-09-05  17670-51384-MA      R-M-1         2
1  QEV-37451-860 2019-09-05  17670-51384-MA    E-M-0.5         5
2  FAA-43335-268 2021-06-17  21125-22134-PX      A-L-1         1
3  KAC-83089-793 2021-07-15  23806-46781-OU      E-M-1         2
4  KAC-83089-793 2021-07-15  23806-46781-OU    R-L-2.5         2

In [10]:
df_cust.head()

,Customer ID,Customer Name,Email,Phone Number,Address Line 1,City,Country,Postcode,Loyalty Card
0,17670-51384-MA,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,United States,7505,Yes
1,73342-18763-UW,Piotr Bote,pbote1@yelp.com,+353 (913) 396-4653,2112 Ridgeway Hill,Crumlin,Ireland,D6W,No
2,21125-22134-PX,Jami Redholes,jredholes2@tmall.com,+1 (210) 986-6806,5214 Bartillon Park,San Antonio,United States,78205,Yes
3,71253-00052-RN,Dene Azema,dazema3@facebook.com,+1 (217) 418-0714,27 Maywood Place,Springfield,United States,62711,Yes
4,23806-46781-OU,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,Ireland,N41,No

In [11]:
df_prod.head()

  Product ID Coffee Type Roast Type  Size  Unit Price  Price per 100g   Profit
0    A-L-0.2         Ara          L   0.2       3.885          1.9425  0.34965
1    A-L-0.5         Ara          L   0.5       7.770          1.5540  0.69930
2      A-L-1         Ara          L   1.0      12.950          1.2950  1.16550
3    A-L-2.5         Ara          L   2.5      29.785          1.1914  2.68065
4    A-M-0.2         Ara          M   0.2       3.375          1.6875  0.30375

In [12]:
df1 = pd.merge(df_ord, df_cust, on = 'Customer ID',how = 'left')

In [13]:
df_all = pd.merge(df1, df_prod, on = 'Product ID',how = 'left')

In [14]:
df_all

,Order ID,Order Date,Customer ID,Product ID,Quantity,Customer Name,Email,Phone Number,Address Line 1,City,Country,Postcode,Loyalty Card,Coffee Type,Roast Type,Size,Unit Price,Price per 100g,Profit
0,QEV-37451-860,2019-09-05,17670-51384-MA,R-M-1,2,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,United States,7505,Yes,Rob,M,1.0,9.950,0.9950,0.59700
1,QEV-37451-860,2019-09-05,17670-51384-MA,E-M-0.5,5,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,United States,7505,Yes,Exc,M,0.5,8.250,1.6500,0.90750
2,FAA-43335-268,2021-06-17,21125-22134-PX,A-L-1,1,Jami Redholes,jredholes2@tmall.com,+1 (210) 986-6806,5214 Bartillon Park,San Antonio,United States,78205,Yes,Ara,L,1.0,12.950,1.2950,1.16550
3,KAC-83089-793,2021-07-15,23806-46781-OU,E-M-1,2,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,Ireland,N41,No,Exc,M,1.0,13.750,1.3750,1.51250
4,KAC-83089-793,2021-07-15,23806-46781-OU,R-L-2.5,2,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,Ireland,N41,No,Rob,L,2.5,27.485,1.0994,1.64910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,RLM-96511-467,2020-01-06,43014-53743-XK,R-L-2.5,1,Jennica Tewelson,jtewelsonrn@samsung.com,+1 (469) 573-8379,4040 Hoard Junction,Dallas,United States,75210,No,Rob,L,2.5,27.485,1.0994,1.64910
996,AEZ-13242-456,2022-05-04,62494-09113-RP,R-M-0.5,5,Marguerite Graves,NaN,+1 (479) 204-9111,91413 Scott Way,Fort Smith,United States,72905,No,Rob,M,0.5,5.970,1.1940,0.35820
997,UME-75640-698,2019-10-11,62494-09113-RP,A-M-0.5,4,Marguerite Graves,NaN,+1 (479) 204-9111,91413 Scott Way,Fort Smith,United States,72905,No,Ara,M,0.5,6.750,1.3500,0.60750
998,GJC-66474-557,2021-08-03,64965-78386-MY,A-D-1,1,Nicolina Jenny,njennyrq@bigcartel.com,+1 (562) 679-4750,6099 American Ash Court,Whittier,United States,90610,No,Ara,D,1.0,9.950,0.9950,0.89550
999,IRV-20769-219,2020-10-15,77131-58092-GE,E-M-0.2,3,Vidovic Antonelli,NaN,+44 (810) 927-9266,3242 Corscot Pass,London,United Kingdom,EC1V,Yes,Exc,M,0.2,4.125,2.0625,0.45375

In [15]:
df_all.shape

(1000, 19)

In [16]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        1000 non-null   object
 1   Order Date      1000 non-null   datetime64[ns]
 2   Customer ID     1000 non-null   object
 3   Product ID      1000 non-null   object
 4   Quantity        1000 non-null   int64
 5   Customer Name   1000 non-null   object
 6   Email           794 non-null    object
 7   Phone Number    865 non-null    object
 8   Address Line 1  1000 non-null   object
 9   City            1000 non-null   object
 10  Country         1000 non-null   object
 11  Postcode        1000 non-null   object
 12  Loyalty Card    1000 non-null   object
 13  Coffee Type     1000 non-null   object
 14  Roast Type      1000 non-null   object
 15  Size            1000 non-null   float64
 16  Unit Price      1000 non-null   float64
 17  Price per 100g  1000 non-null   float64
 18  Profit          1000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(13)
memory usage: 156.2+ KB

In [23]:
df = df_all.copy()

In [28]:
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month
df['Day'] = df['Order Date'].dt.day
df['WeekDay'] = df['Order Date'].dt.day_name()

In [29]:
df

,Order ID,Order Date,Customer ID,Product ID,Quantity,Customer Name,Email,Phone Number,Address Line 1,City,...,Coffee Type,Roast Type,Size,Unit Price,Price per 100g,Profit,Year,Month,Day,WeekDay
0,QEV-37451-860,2019-09-05,17670-51384-MA,R-M-1,2,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,...,Rob,M,1.0,9.950,0.9950,0.59700,2019,9,5,Thursday
1,QEV-37451-860,2019-09-05,17670-51384-MA,E-M-0.5,5,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,...,Exc,M,0.5,8.250,1.6500,0.90750,2019,9,5,Thursday
2,FAA-43335-268,2021-06-17,21125-22134-PX,A-L-1,1,Jami Redholes,jredholes2@tmall.com,+1 (210) 986-6806,5214 Bartillon Park,San Antonio,...,Ara,L,1.0,12.950,1.2950,1.16550,2021,6,17,Thursday
3,KAC-83089-793,2021-07-15,23806-46781-OU,E-M-1,2,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,...,Exc,M,1.0,13.750,1.3750,1.51250,2021,7,15,Thursday
4,KAC-83089-793,2021-07-15,23806-46781-OU,R-L-2.5,2,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,...,Rob,L,2.5,27.485,1.0994,1.64910,2021,7,15,Thursday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,RLM-96511-467,2020-01-06,43014-53743-XK,R-L-2.5,1,Jennica Tewelson,jtewelsonrn@samsung.com,+1 (469) 573-8379,4040 Hoard Junction,Dallas,...,Rob,L,2.5,27.485,1.0994,1.64910,2020,1,6,Monday
996,AEZ-13242-456,2022-05-04,62494-09113-RP,R-M-0.5,5,Marguerite Graves,NaN,+1 (479) 204-9111,91413 Scott Way,Fort Smith,...,Rob,M,0.5,5.970,1.1940,0.35820,2022,5,4,Wednesday
997,UME-75640-698,2019-10-11,62494-09113-RP,A-M-0.5,4,Marguerite Graves,NaN,+1 (479) 204-9111,91413 Scott Way,Fort Smith,...,Ara,M,0.5,6.750,1.3500,0.60750,2019,10,11,Friday
998,GJC-66474-557,2021-08-03,64965-78386-MY,A-D-1,1,Nicolina Jenny,njennyrq@bigcartel.com,+1 (562) 679-4750,6099 American Ash Court,Whittier,...,Ara,D,1.0,9.950,0.9950,0.89550,2021,8,3,Tuesday
999,IRV-20769-219,2020-10-15,77131-58092-GE,E-M-0.2,3,Vidovic Antonelli,NaN,+44 (810) 927-9266,3242 Corscot Pass,London,...,Exc,M,0.2,4.125,2.0625,0.45375,2020,10,15,Thursday

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        1000 non-null   object
 1   Order Date      1000 non-null   datetime64[ns]
 2   Customer ID     1000 non-null   object
 3   Product ID      1000 non-null   object
 4   Quantity        1000 non-null   int64
 5   Customer Name   1000 non-null   object
 6   Email           794 non-null    object
 7   Phone Number    865 non-null    object
 8   Address Line 1  1000 non-null   object
 9   City            1000 non-null   object
 10  Country         1000 non-null   object
 11  Postcode        1000 non-null   object
 12  Loyalty Card    1000 non-null   object
 13  Coffee Type     1000 non-null   object
 14  Roast Type      1000 non-null   object
 15  Size            1000 non-null   float64
 16  Unit Price      1000 non-null   float64
 17  Price per 100g  1000 non-null   float64
 18  Profit          1000 non-null   float64
 19  Year            1000 non-null   int64
 20  Month           1000 non-null   int64
 21  Day             1000 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(4), object(13)
memory usage: 179.7+ KB

In [27]:
df.isnull()

,Order ID,Order Date,Customer ID,Product ID,Quantity,Customer Name,Email,Phone Number,Address Line 1,City,...,Loyalty Card,Coffee Type,Roast Type,Size,Unit Price,Price per 100g,Profit,Year,Month,Day
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [30]:
list(df['Coffee Type'].unique())

['Rob', 'Exc', 'Ara', 'Lib']

In [31]:
list(df['Roast Type'].unique())

['M', 'L', 'D']

In [32]:
list(df['Size'].unique())

[1.0, 0.5, 2.5, 0.2]

In [33]:
df.replace({
    'Roast Type': {'L': 'Light', 'M': 'Medium', 'D': 'Dark'},
    'Coffee Type': {'Ara': 'Arabica', 'Rob': 'Robusta', 'Exc': 'Excelsa', 'Lib': 'Liberica'}
}, inplace=True)

In [34]:
df

,Order ID,Order Date,Customer ID,Product ID,Quantity,Customer Name,Email,Phone Number,Address Line 1,City,...,Coffee Type,Roast Type,Size,Unit Price,Price per 100g,Profit,Year,Month,Day,WeekDay
0,QEV-37451-860,2019-09-05,17670-51384-MA,R-M-1,2,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,...,Robusta,Medium,1.0,9.950,0.9950,0.59700,2019,9,5,Thursday
1,QEV-37451-860,2019-09-05,17670-51384-MA,E-M-0.5,5,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,...,Excelsa,Medium,0.5,8.250,1.6500,0.90750,2019,9,5,Thursday
2,FAA-43335-268,2021-06-17,21125-22134-PX,A-L-1,1,Jami Redholes,jredholes2@tmall.com,+1 (210) 986-6806,5214 Bartillon Park,San Antonio,...,Arabica,Light,1.0,12.950,1.2950,1.16550,2021,6,17,Thursday
3,KAC-83089-793,2021-07-15,23806-46781-OU,E-M-1,2,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,...,Excelsa,Medium,1.0,13.750,1.3750,1.51250,2021,7,15,Thursday
4,KAC-83089-793,2021-07-15,23806-46781-OU,R-L-2.5,2,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,...,Robusta,Light,2.5,27.485,1.0994,1.64910,2021,7,15,Thursday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,RLM-96511-467,2020-01-06,43014-53743-XK,R-L-2.5,1,Jennica Tewelson,jtewelsonrn@samsung.com,+1 (469) 573-8379,4040 Hoard Junction,Dallas,...,Robusta,Light,2.5,27.485,1.0994,1.64910,2020,1,6,Monday
996,AEZ-13242-456,2022-05-04,62494-09113-RP,R-M-0.5,5,Marguerite Graves,NaN,+1 (479) 204-9111,91413 Scott Way,Fort Smith,...,Robusta,Medium,0.5,5.970,1.1940,0.35820,2022,5,4,Wednesday
997,UME-75640-698,2019-10-11,62494-09113-RP,A-M-0.5,4,Marguerite Graves,NaN,+1 (479) 204-9111,91413 Scott Way,Fort Smith,...,Arabica,Medium,0.5,6.750,1.3500,0.60750,2019,10,11,Friday
998,GJC-66474-557,2021-08-03,64965-78386-MY,A-D-1,1,Nicolina Jenny,njennyrq@bigcartel.com,+1 (562) 679-4750,6099 American Ash Court,Whittier,...,Arabica,Dark,1.0,9.950,0.9950,0.89550,2021,8,3,Tuesday
999,IRV-20769-219,2020-10-15,77131-58092-GE,E-M-0.2,3,Vidovic Antonelli,NaN,+44 (810) 927-9266,3242 Corscot Pass,London,...,Excelsa,Medium,0.2,4.125,2.0625,0.45375,2020,10,15,Thursday

In [35]:
df = df.drop('Price per 100g',axis=1)

In [36]:
df

,Order ID,Order Date,Customer ID,Product ID,Quantity,Customer Name,Email,Phone Number,Address Line 1,City,...,Loyalty Card,Coffee Type,Roast Type,Size,Unit Price,Profit,Year,Month,Day,WeekDay
0,QEV-37451-860,2019-09-05,17670-51384-MA,R-M-1,2,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,...,Yes,Robusta,Medium,1.0,9.950,0.59700,2019,9,5,Thursday
1,QEV-37451-860,2019-09-05,17670-51384-MA,E-M-0.5,5,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,...,Yes,Excelsa,Medium,0.5,8.250,0.90750,2019,9,5,Thursday
2,FAA-43335-268,2021-06-17,21125-22134-PX,A-L-1,1,Jami Redholes,jredholes2@tmall.com,+1 (210) 986-6806,5214 Bartillon Park,San Antonio,...,Yes,Arabica,Light,1.0,12.950,1.16550,2021,6,17,Thursday
3,KAC-83089-793,2021-07-15,23806-46781-OU,E-M-1,2,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,...,No,Excelsa,Medium,1.0,13.750,1.51250,2021,7,15,Thursday
4,KAC-83089-793,2021-07-15,23806-46781-OU,R-L-2.5,2,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,...,No,Robusta,Light,2.5,27.485,1.64910,2021,7,15,Thursday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,RLM-96511-467,2020-01-06,43014-53743-XK,R-L-2.5,1,Jennica Tewelson,jtewelsonrn@samsung.com,+1 (469) 573-8379,4040 Hoard Junction,Dallas,...,No,Robusta,Light,2.5,27.485,1.64910,2020,1,6,Monday
996,AEZ-13242-456,2022-05-04,62494-09113-RP,R-M-0.5,5,Marguerite Graves,NaN,+1 (479) 204-9111,91413 Scott Way,Fort Smith,...,No,Robusta,Medium,0.5,5.970,0.35820,2022,5,4,Wednesday
997,UME-75640-698,2019-10-11,62494-09113-RP,A-M-0.5,4,Marguerite Graves,NaN,+1 (479) 204-9111,91413 Scott Way,Fort Smith,...,No,Arabica,Medium,0.5,6.750,0.60750,2019,10,11,Friday
998,GJC-66474-557,2021-08-03,64965-78386-MY,A-D-1,1,Nicolina Jenny,njennyrq@bigcartel.com,+1 (562) 679-4750,6099 American Ash Court,Whittier,...,No,Arabica,Dark,1.0,9.950,0.89550,2021,8,3,Tuesday
999,IRV-20769-219,2020-10-15,77131-58092-GE,E-M-0.2,3,Vidovic Antonelli,NaN,+44 (810) 927-9266,3242 Corscot Pass,London,...,Yes,Excelsa,Medium,0.2,4.125,0.45375,2020,10,15,Thursday

In [44]:
df['Revenue'] = df['Unit Price'] * df['Quantity']

In [45]:
df

,Order ID,Order Date,Customer ID,Product ID,Quantity,Customer Name,Email,Phone Number,Address Line 1,City,...,Coffee Type,Roast Type,Size,Unit Price,Profit,Year,Month,Day,WeekDay,Revenue
0,QEV-37451-860,2019-09-05,17670-51384-MA,R-M-1,2,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,...,Robusta,Medium,1.0,9.950,0.59700,2019,9,5,Thursday,19.900
1,QEV-37451-860,2019-09-05,17670-51384-MA,E-M-0.5,5,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,...,Excelsa,Medium,0.5,8.250,0.90750,2019,9,5,Thursday,41.250
2,FAA-43335-268,2021-06-17,21125-22134-PX,A-L-1,1,Jami Redholes,jredholes2@tmall.com,+1 (210) 986-6806,5214 Bartillon Park,San Antonio,...,Arabica,Light,1.0,12.950,1.16550,2021,6,17,Thursday,12.950
3,KAC-83089-793,2021-07-15,23806-46781-OU,E-M-1,2,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,...,Excelsa,Medium,1.0,13.750,1.51250,2021,7,15,Thursday,27.500
4,KAC-83089-793,2021-07-15,23806-46781-OU,R-L-2.5,2,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,...,Robusta,Light,2.5,27.485,1.64910,2021,7,15,Thursday,54.970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,RLM-96511-467,2020-01-06,43014-53743-XK,R-L-2.5,1,Jennica Tewelson,jtewelsonrn@samsung.com,+1 (469) 573-8379,4040 Hoard Junction,Dallas,...,Robusta,Light,2.5,27.485,1.64910,2020,1,6,Monday,27.485
996,AEZ-13242-456,2022-05-04,62494-09113-RP,R-M-0.5,5,Marguerite Graves,NaN,+1 (479) 204-9111,91413 Scott Way,Fort Smith,...,Robusta,Medium,0.5,5.970,0.35820,2022,5,4,Wednesday,29.850
997,UME-75640-698,2019-10-11,62494-09113-RP,A-M-0.5,4,Marguerite Graves,NaN,+1 (479) 204-9111,91413 Scott Way,Fort Smith,...,Arabica,Medium,0.5,6.750,0.60750,2019,10,11,Friday,27.000
998,GJC-66474-557,2021-08-03,64965-78386-MY,A-D-1,1,Nicolina Jenny,njennyrq@bigcartel.com,+1 (562) 679-4750,6099 American Ash Court,Whittier,...,Arabica,Dark,1.0,9.950,0.89550,2021,8,3,Tuesday,9.950
999,IRV-20769-219,2020-10-15,77131-58092-GE,E-M-0.2,3,Vidovic Antonelli,NaN,+44 (810) 927-9266,3242 Corscot Pass,London,...,Excelsa,Medium,0.2,4.125,0.45375,2020,10,15,Thursday,12.375